image: python:3.6

stages:
  - infra
  - apps
  - test
  - deploy

before_script:
  - source environment
  - apt-get -y update
  - apt-get -y install jq moreutils curl unzip zip
  - mkdir ./external_binaries
  - curl https://releases.hashicorp.com/terraform/0.12.17/terraform_0.12.17_linux_amd64.zip -o /tmp/terraform.zip
  - unzip /tmp/terraform.zip -d ./external_binaries/
  - rm /tmp/terraform.zip
  - export PATH=$PATH:`pwd`/external_binaries/
  - pip install awscli --upgrade
  - pip install boto3 --upgrade
  - pip install virtualenv
  - export AWS_DEFAULT_REGION='us-east-1'
  - make secrets
  - export GOOGLE_APPLICATION_CREDENTIALS="${PROJECT_ROOT}/gcp-credentials-logs-travis.json"

infra:
  stage: infra
  script:
    - make init-infrastructure
    - make plan-infrastructure

apps:
  stage: apps
  script:
    - make init-apps
    - make install
    - make plan-apps

test:
  stage: test
  script:
    - make install
    - make test

deploy:
  stage: deploy
  only:
    - master
  script:
    - make init
    - make deploy
