language: python
cache:
  pip: true
  directories:
  - apps/gcp_to_cwl/venv
  - apps/es_idx_manager/venv
  - apps/cwl_firehose_subscriber/venv
  - apps/firehose_to_es_processor/venv
python:
- 3.6
dist: trusty
addons:
  apt:
    packages:
    - jq
    - curl
    - unzip
    - moreutils
before_install:
- make decrypt
- source config/environment_dev
- mkdir ./external_binaries
- curl https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
  -o /tmp/terraform.zip
- unzip /tmp/terraform.zip -d ./external_binaries/
- rm /tmp/terraform.zip
- export PATH=$PATH:`pwd`/external_binaries/
- pip install awscli --upgrade
- pip install boto3 --upgrade
install:
- source config/environment_dev
- make init
- make install
script:
- source config/environment_dev
- GOOGLE_APPLICATION_CREDENTIALS=`pwd`/config/gcp-credentials-logs-travis.json make
  infrastructure-plan
- make test
deploy:
- provider: script
  script: ". config/environment_dev ; make is-deployed"
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  # aws access key id
  - secure: E0u1Zuqs6pmHSReyLBFpLNk47QnqVnSU7n8WxJ2giiOBD7rjSVA2yd9qHgI2PYvMx1kZv1yBFcPoQ9qhqF0k5HUThZjTCFO4h0qlrSTiAwcwQ2/SGws7288tHZtIvLeDHOc1bMceoKb3rZDDjaomQIghL8rBdklJ1IHYebsG7Lt29+s/jhUCVB7r7OMtwhRQrIW/P9rnaG9TXmBqq7JlR320RrCsUnfysxoojLTIL1KJUK89+wsYPosEoCbcOxtxffTCCZVpaAdzORIfjLBgJKJH94ndxrZ1gq3ARhro/0nmgM/BG7z+pkWRSaK5e0BYxJojuOXT3lfxXz7aW08G+mbn16bIRc3eD7l2M3DKW6MbG9xd4TycCbhRgEW+D+8sf1uQYE3OfeGI1/UIq6Z0IKTdNptJ2wvsMkWmLdcJaUJPytR1C7RXgE2UC2qoNYPnfzaKjM6CZBorXXwPhnCEqSPpQL7CbVf9CQnbLIc2EGUVCsI8n6LbOpGHyAkyQDAOyCAhifOG/AwnaFXpDFb4e8nAbuA2+z1h8atCs6GF+G7WP9yGnh1D31lmpexkfAKwFVc6MOtPOJ3qLNKcIQ0lTURvMLq8zmpc61sZHIf4iDN8N97vlAUowBewHt3qgYyLJAW28Wh30vBc1P64jOFkGC5Zp9Ce1/rVC13MoyfV2bk=
  # aws secret access key
  - secure: RgyEmqzOpwwuIT3Ffgi6LXnM6cP3VUKA43BvLqBmhQ5uYLGCyjqLbdpRQ1nPd5tRqCBOhlqmG3OfPbLNvWQMwKh3OUKgtE6M0oWEkH5ghuAblgoiQuw9jkVI+xwpr/pnQZUzCZJl+YdLeRoso4vao3/dRXR54LTUHkvy3B838b2I0giBTUdWJt0q8Y1+Dd2TfTaSbZwHEY86gRQif8c7/q0+dVV/0SXlsKdKGq3od4KIWe7Wtp+v9drqX8ywV9KvdBVgoq6FrDQ6k98Ev4hx6VPeW2jWIoXTxU0C1uHS6f1IEI0AZT5imAZrMNB6zpvUAV7AvNuzGJJGl9d82wzyQE8tS0UAWchUWrDKDCp5Q/wASnXFyVg7wswYqNcgF5m6G7EhXN19OiVc1lzsQfppc8q6Li/JxybcW0o+FI+bpIZuNJSZsy3eqD3vUVFC8zpdFoszVmnd3LB2R65QY/2mom3Fghs3EGpVmVgyfZiBGy9qLLKDmnmWaVtzMIbEzNZaEksNVZNaSOcyZvCUnN9M8lbjEWwBV4aUSS2APd5abJ9SbKr9rJa212fONIR++1GCv6uJYNxtO5ZHVcS4tSCvVYN1SKTDHLxGzmgKVaNEISqvWCLhY9zAiCg91XZKKokJKp4ts82rC1Ipr3zKD8e5FpEH67Ts2I506GRnTtQ6erk=
  # aws default region
  - secure: FdbdGB/PqfSxNvRoAZpO2nSERNZgYqU6rn+43EC0PWK+GrcQqlOIiYXLL4ZYRmZLH62zHq8ZvKFlBAWBxGxdCQUK0FM8tHXQPIICDehq/VahCFOoxocbtFA/jdfSpioZeTBiFyiiA2eUv53ZkTlYkda6TVITiYmpZTQ1w1INa3oaNXoD9LpjdwBqEhJ+H6qkB2G1gGjBNTqCcQ3kSYS7KWbFiXBIXo8ux/DYie2k3E/IsCHqvVCPQVGMTtPuwOQgdOHjlxgwnjew2tbA7GTCDuVtYwD8qj7ixOyOy6PXBEV8MqMIywcgTIGXo7msRJJtKuWaTKxhzwsj2gvxq9OwOI8sDODgA9E/4OucDoD6S9lBmZNShizbFSbdAcx7Rm984gF2eMdNoGhI+NC61HYz6HXDPucPz5RhF2yKRieRiECWCxYMMl/09zOG3Z4B94Q4pXFRdDr8rBXCNNgqj1a5o3DQCDzntJ0h8iRKUQHl6hAdggRH1O9vG904fbIct2T20rfh7CHfvWndeHNeoOjwms2lEYqf5/mZ22PX2wwyOWicikBlfJZp42z4gJOK1p+5dsp5GJxg2CiOvJrGODTU5+QzChwgDhDIKZ7f31Q8Fgs6/x1jQzsN7TT8wuUZYUrWC32ocHlVl6VWxNZj0g6hGcgCsFS/++Z1wqwcE4ARuEI=
  - secure: J+OU+4hXw21ADKHKgqleap85rqJt1q1TW3OymP256AKOQVfMvivaxh2gVzCtWGmkspCDNeXPBxVwA0xtlUHTybGasoOnGamTmuwgFaNkjopkk2mwdHpim4xc4MZO0O49b2nXdKxYhUIbyfJXqINv6MJA/pTYl8dnm858KTsuFxz2gng6na+9fWYfxKsbLvEzW8WsrctaCIWrZi1dZ0evHuAzMzWr69KoxmxxIIkPGcNL3hpRRB2MB8nZh0EyhEi1VZ99rlMohdDYEopm2jaEBBFRPwnJrAYGtFZn4kwj+Lq52pCk69S7b3Mvd365iQXD1A6IegOTLELHkoArD3danIZYzRptTKMb2CYTnUtGuBCZY7DWaF2giglevDR9B7fU39reCKng1FniT0OI9jz9dmgI/OagqLeXe+N37PAb5syJFnhqlbdB0qQOfHfkr4bA7IdKlkKCZfaTqTRnuxz/hdEe91sMUwCZ3P9Xev8+ZEt5WC+zkWbNh6xhVzlvpyoVHYkqcr0w6ezwlVzZJVXbnDRk/FTX3d8cWKoVX6mGJWYAr2aiadqF0ouIgoHkvf0qzoP042PuTBBg602rFbnA1lJt1dfcwb8S0xRZTje8Lm7TDQH1FrBX21cUvJz6DXTRHVGE6Z/k9xZEBP/eCJgDlNVoD4a/Kjr7vrTsSRGZavw=
