language: python
cache:
  pip: true
  directories:
  - exporters/gcp_to_cwl/venv
  - es_managers/es_idx_manager/venv
python:
- 3.6
dist: trusty
addons:
  apt:
    packages:
    - jq
    - curl
    - unzip
    - moreutils
before_install:
- make decrypt
- source config/environment
- mkdir ./external_binaries
- curl https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip
  -o /tmp/terraform.zip
- unzip /tmp/terraform.zip -d ./external_binaries/
- rm /tmp/terraform.zip
- export PATH=$PATH:`pwd`/external_binaries/
- pip install awscli --upgrade
- pip install boto3 --upgrade
install:
- make init
- make install
script:
- source config/environment
- make infrastructure-plan
- make test
deploy:
- provider: script
  script: export DEPLOYMENT_STAGE=staging ; make deploy
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: WpGG7X2h13GPWi63T7KMYus8YV8v/X4sYYMEdcKkK9j+x1r/CjArdAeh2zrqEtMWVzb0I6AR/wyOh+iXx7MmQaMyRVhrkePBGTIg1BjHs3CPTyIWk5J7DvKohBfg4pE6ABJHvE+B1zO14d+LDfBu0yq08yagGaaz7Ru5KRCq8/w9qoiLR6RleU4Wgdhd/0bIQHryysA5D/zd7meyMtgyYo0PDAlBkpkZA5buxpzqWnflVdAKiV1dBVmrOG4U7TsRgzXJhUoiZ3m70JozbRsa8oz90el/7ziDVydfJm25seHOwnKeRSogFQ/kCChUH7zho9+8FVfovqZpdut6ifkeT2jsyu3bXmvTshku+QN+BPxD9ACCLMfWQWI532jGd2giOM2WyN8EzeudLH789LpHIFuJny3uhx75yvPvrsuDPlB9qArwIMC42iXxGV6uYlwTQSTsyzF6OS/mKOxSveq5JN8VoWatHqc/QsM3iIoG5pdMQ9ijDPW5eFWfVrL26xyAnCYqlxVNS22U1dtYBBipV33T406QgBRsb5IwnMitbry4NHbHGrnDgjGo6vvZX//WQTII755ALXuzJ7gHtK+XJGQ7fAt+I6eCgQH0MLGGqJnLriLrEujEvQUJ9etI6rtrO+UNjqXl4Yajs7mlZpGaedpHeXg9Ly8hx089IvtUK5Y=
  - secure: NnSatNdCpT1KpEL2j74zr2jGJ62Dw5ua48x7dp9MV7LttZX9eEFYSAlSUTr/nG+LLsctC/RjqnUN1mjuQO4Fy/BmJF4wfqkNrLpLVL+2YZhA3NDs5hUsRAeKHK2w5rta7yHBDo9hF6K6pml+/QGImuMVDW9mahlAWk5cg5QIvxx7HhM2L2IkVBwAvEVfnNQItk3CFPPVdY7fK6QXVxJNxIecZPTbJVnONphrSNOPzull5bqHaCW8BE5I7F93W78uCXpJ+smmjtbFcaOMSAt2bcgOyia+/laDLzQezwFi3lqNsi1FQCYjuzwtkCyIYMLkEHZOShFh9ecbwBAb+TQdEQxybF0ogeEITV8POS9G3EM91E+h6sL5YBpUupcJTdwF9N5nk+EttiuGbowPVxCbb/4+Jw30YDmD0ORZIKEL6Z8tRToZtNksSv55Hnk5zER3DBFLkP+48KTHclEsOYI3roy39zr3ZZjlq2krIInEET9F5OfaNoQ2txBJ10T+2cf6yRNIZPjk+YOFo0YfToFEoBrsIl/zBLleUDclAvB2ehiHRxX2HNtFWJqfghFSnDKrbEa7qwSqByG68teJMloLJD+Q6Wg2QaypDyj84uWpa9lmkI9+2GscH6zb4Iw87OAo209bmgWlrS0upcsUq4pZLd+WErz+TtFji5wmx38Wd1c=
  - secure: qk6dPEp2FuvPsTu6O6v8i7BYzS6LYl0ikpxcjZYzVIqqDjjyay1vWdUG3D2in8dfCIBt+p+dtQaY9uGeinWBvmN+dqp3JptShx8TU8ajyjYEMtbFZTgWcyFLPAU6GdS4LoDM+h0Ne5hmg3QBZUOmXasstInNMoawdblVWIQ8sS5Nu5brq4R8c7GxZaNs3dZ6MkMtFGpA0wc+syWFe0aQW6p/MS5KV2ndRdGreC4UOpyBuWJJKxebJ32QsQBuDv64WunuqokeIRAWJMOs70scnoQv2JbGIFKLfEZ4eEFZnBf6jc5gcXui/T4CT3g8BgJdNaNzSZvyf6Ue/FWjkdNWRYJq97bd2CoMCP6trgnM3NznB3q0jORQmkYpU3ubz2PSJsdLJ26Bhupv5wOSjFZ5afW3Xrbe0LTWd98OiYJ5eMIZq/UDa/jxlAVnfiI9pd2L01o5voazJqmZUPFNJq+Ak7YQqaicN7jrBesllrqm1K9JNhO+eEDgobpIp9/XGyI8buveT/QoP80KJGjLvcu7/gsod53syAUPKmw+NS4Kj467WfkSWTi0jsERZVLcj5ZFMxULvulqAWdHzzZBfS9Z1MZOiprNFK7X29y7dUSq/d81eF6ZBHNtKjs5eT84FS2DFKqfMDSBv4rziBMI30803cwB3CjZ+WesPI2ayAmc87k=
  - secure: PXY7bV5xuYTdtGO8Y3gfy9xXpn0j9rCedWY7/bySY5/lUSju2BuGIfYaGevrENUDFqoExPB4sQgK7Vy86x8ftsxQuEk5pV11d5yL8wqvIQ39gn7vtEzDuG9+lO02aTrBKbvtLf7ivVDFWwdwRkjW9m5170kf8GTXy4LJ2BH2KdLEjEb2uPhuDaDyGyB5EfTRA7aHB2GQg890seGT2jfjVyk+BvYYopUBG/rXG+PlR/rjTdac3bvKJ/Nr8vtKxV/NeDBgiBeA+nFd0F8/2SMZROWIXAqFKLhumkXm6TR+qStEovDFO68SBI7oU1wU5q6CyR4hkWgG1wjgUQoVnAJbsZBmRAtemmd2FH3m2PyHge1Z6lhDtTa1T1ETIwM2VrpCWebpodnhsgNf9EiOhJmgsK1wvuPQCEtzTrEF9QfniLG2OG3bn4Eqtzo7YXGRgYCi1FXf4djgml+830ZwIGNpjE34loaCiCAJJYEe2LqQUcqj/rB7G/UGXdGZWyeJW2+LSKgk9cEkVRsNaWGQwco7s6nHID6N4Hp+CVFvC6sQbFAmRdphFNhAOBTm/2HBBPCs47zeqQPrHtWc7GFZxBsBEDGgcMSRIlG0IODor2fdGXpE5GDT7iAkC/W6oQm+wUKpQjlBHnyP9iboXTu7Nodv+/as+dBqJRzEz3LBQknHXvo=
