- name: elastic search human cell atlas
  days: 14
  index_format: '%Y-%m-%d'
  indices:
    - prefix: cwl

- name: test configuration
  days: 7
  index_format: '%Y-%m-%d'
  indices:
    - prefix: test
