#!/usr/bin/env bash
set -a
# hardcoded or derived variables
PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
ACCOUNT_ID=${ACCOUNT_ID:-$(aws sts get-caller-identity | jq -r .Account)}

# user defined or sensitive variables
ENCRYPTION_KEY=undefined
AWS_DEFAULT_REGION=undefined
BLACKLISTED_LOG_GROUPS=undefined
CLOUDTRAIL_LOG_GROUP_NAME=undefined
CLOUDTRAIL_NAME=undefined
CLOUDTRAIL_S3_BUCKET=undefined
DEPLOYMENT_STAGE=undefined
ES_AUTHORIZED_EMAILS_FILE=undefined
ES_DOMAIN_NAME=undefined
ES_IDX_MANAGER_SETTINGS=undefined
GCLOUD_PROJECT=undefined
GCP_LOG_TOPIC_SUBSCRIPTION_NAME=undefined
GCP_LOGS_PROJECT_NAME=undefined
GCP_PUBSUB_AUTHORIZED_SERVICE_ACCOUNTS_FILE=undefined
GCP_REGION=undefined
GCP_EXPORTER_GOOGLE_APPLICATION_CREDENTIALS=undefined
TERRAFORM_BUCKET=undefined
TRAVIS_USER=undefined
AIRBRAKE_BLACKLISTED_LOG_GROUP_NAMES=undefined
AIRBRAKE_WHITELISTED_LOG_MESSAGE_TERMS=undefined
AIRBRAKE_FLAG=undefined
AIRBRAKE_API_KEY=undefined
AIRBRAKE_PROJECT_ID=undefined
AIRBRAKE_ENVIRONMENT=undefined

ES_AUTHORIZED_EMAILS="[$(cat $ES_AUTHORIZED_EMAILS_FILE | awk '{ print "\""$0"\""}' | tr '\n' ',')]"
GCP_PUBSUB_AUTHORIZED_SERVICE_ACCOUNTS="[$(cat $GCP_PUBSUB_AUTHORIZED_SERVICE_ACCOUNTS_FILE | awk '{ print "\""$0"\""}' | tr '\n' ',')]"
ES_ENDPOINT=$(aws es describe-elasticsearch-domain --domain $ES_DOMAIN_NAME | jq -r '.DomainStatus.Endpoint')
set +a
